name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.28
  audio_session: ^0.0.11
  just_audio: ^0.6.15+1
  flutter_tts: ^2.1.0
  rxdart: 0.24.1
  audio_service:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true